sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MAYj38GdEuK6VmZ0wKk+54jPkmY/ASI3jU5vx0U3x2kGf+w/gUaAQnUEFluBkHFzFvDN7rUl5GA1ZyORixnPmCNuuEVY5UBIOLwKfpUtdDu5yu9IqfnTPCsy//w6/yUVBcLzi6SaZxmJDNiRLoOBMPmRGcbH3yQd1JD9HJ3kRmbveBotAAFq/yfzZiyuXeZaIXgVPlazD/zWWfzqPk5HpkYPjKbV/w6Sz2uByGB5TEZSV3aUGLz0RwSedYLmQmZFoXEo+eudzKL3xEacjQUXTRRrzXZniPUyE7C3kGi3qOHzF88LKsH52DLVQkgEbSjSmjRGRdLvL3/7nmQUNQv1Kwqk5L52Wg1BRWigpRXS6Nn29huze9Yc6vCAhTlLYHzht6RNSQ7YF45g9VvlXzWCKE7ug8MuIhPyzRcoRfROoPH2p0zqWeN8n9iV6x8s3IVz+0S1yIEt5o1FwYWNsruigNupdhwStXIDIssAxXffUepUh+4PLJzhPc9wnIAuIiZo39xz5XbheVM4EF3bA0PN9r3eTjGi21lThbuDC+IAiVu+Bdbg2r9OtFT/74dVwQbzierEhgMsBIdHV43OyTdjJasYuWxovrPyFbJ4j0Ry3U3ayhpVQe0jj0txa2eCmyVifY0kpjWrV25NFqu+GyvcQHVWMsTt7+qgzksZLQUT1IY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Pocket-R.L.S.--Being-Favourite-Passages-from-the-Works-of-Stevenson_2537
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy